#############################################################################
# Makefile for building: Biblioteca
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  Biblioteca.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Biblioteca.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Biblioteca1.0.0
DISTDIR = /home/aldo/Scrivania/Biblioteca/build/obj/Biblioteca1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/gui/AdminDetailPage.cpp \
		src/gui/AdminPage.cpp \
		src/gui/BaseDetailPage.cpp \
		src/gui/BasePage.cpp \
		src/gui/EditMediaDialog.cpp \
		src/gui/GalleryWidget.cpp \
		src/gui/MediaBox.cpp \
		src/gui/MediaDialog.cpp \
		src/gui/SearchWidget.cpp \
		src/gui/LoginPage.cpp \
		src/gui/MainWindow.cpp \
		src/gui/UserDetailPage.cpp \
		src/gui/UserPage.cpp \
		src/model/media/audiolibro.cpp \
		src/model/media/biblioteca.cpp \
		src/model/media/cd.cpp \
		src/model/media/fumetto.cpp \
		src/model/media/libro.cpp \
		src/model/media/media_audio.cpp \
		src/model/media/media_cartaceo.cpp \
		src/model/media/media_video.cpp \
		src/model/media/multimedia.cpp \
		src/model/media/periodico.cpp \
		src/model/media/serie_tv.cpp \
		src/model/persistence/JsonManager.cpp \
		src/model/visitors/VisitorWidget.cpp build/moc/moc_AdminPage.cpp \
		build/moc/moc_AdminDetailPage.cpp \
		build/moc/moc_BaseDetailPage.cpp \
		build/moc/moc_BasePage.cpp \
		build/moc/moc_EditMediaDialog.cpp \
		build/moc/moc_GalleryWidget.cpp \
		build/moc/moc_MediaBox.cpp \
		build/moc/moc_MediaDialog.cpp \
		build/moc/moc_SearchWidget.cpp \
		build/moc/moc_LoginPage.cpp \
		build/moc/moc_MainWindow.cpp \
		build/moc/moc_UserDetailPage.cpp \
		build/moc/moc_UserPage.cpp \
		build/moc/moc_JsonManager.cpp \
		build/moc/moc_VisitorWidget.cpp
OBJECTS       = build/obj/main.o \
		build/obj/AdminDetailPage.o \
		build/obj/AdminPage.o \
		build/obj/BaseDetailPage.o \
		build/obj/BasePage.o \
		build/obj/EditMediaDialog.o \
		build/obj/GalleryWidget.o \
		build/obj/MediaBox.o \
		build/obj/MediaDialog.o \
		build/obj/SearchWidget.o \
		build/obj/LoginPage.o \
		build/obj/MainWindow.o \
		build/obj/UserDetailPage.o \
		build/obj/UserPage.o \
		build/obj/audiolibro.o \
		build/obj/biblioteca.o \
		build/obj/cd.o \
		build/obj/fumetto.o \
		build/obj/libro.o \
		build/obj/media_audio.o \
		build/obj/media_cartaceo.o \
		build/obj/media_video.o \
		build/obj/multimedia.o \
		build/obj/periodico.o \
		build/obj/serie_tv.o \
		build/obj/JsonManager.o \
		build/obj/VisitorWidget.o \
		build/obj/moc_AdminPage.o \
		build/obj/moc_AdminDetailPage.o \
		build/obj/moc_BaseDetailPage.o \
		build/obj/moc_BasePage.o \
		build/obj/moc_EditMediaDialog.o \
		build/obj/moc_GalleryWidget.o \
		build/obj/moc_MediaBox.o \
		build/obj/moc_MediaDialog.o \
		build/obj/moc_SearchWidget.o \
		build/obj/moc_LoginPage.o \
		build/obj/moc_MainWindow.o \
		build/obj/moc_UserDetailPage.o \
		build/obj/moc_UserPage.o \
		build/obj/moc_JsonManager.o \
		build/obj/moc_VisitorWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Biblioteca.pro src/gui/AdminPage.h \
		src/gui/AdminDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/gui/BasePage.h \
		src/gui/EditMediaDialog.h \
		src/gui/GalleryWidget.h \
		src/gui/MediaBox.h \
		src/gui/MediaDialog.h \
		src/gui/SearchWidget.h \
		src/gui/LoginPage.h \
		src/gui/MainWindow.h \
		src/gui/UserDetailPage.h \
		src/gui/UserPage.h \
		src/model/media/audiolibro.h \
		src/model/media/biblioteca.h \
		src/model/media/cd.h \
		src/model/media/fumetto.h \
		src/model/media/libro.h \
		src/model/media/media_audio.h \
		src/model/media/media_cartaceo.h \
		src/model/media/media_video.h \
		src/model/media/multimedia.h \
		src/model/media/periodico.h \
		src/model/media/serie_tv.h \
		src/model/observers/JsonObserver.h \
		src/model/persistence/JsonManager.h \
		src/model/visitors/Visitor.h \
		src/model/visitors/VisitorWidget.h src/main.cpp \
		src/gui/AdminDetailPage.cpp \
		src/gui/AdminPage.cpp \
		src/gui/BaseDetailPage.cpp \
		src/gui/BasePage.cpp \
		src/gui/EditMediaDialog.cpp \
		src/gui/GalleryWidget.cpp \
		src/gui/MediaBox.cpp \
		src/gui/MediaDialog.cpp \
		src/gui/SearchWidget.cpp \
		src/gui/LoginPage.cpp \
		src/gui/MainWindow.cpp \
		src/gui/UserDetailPage.cpp \
		src/gui/UserPage.cpp \
		src/model/media/audiolibro.cpp \
		src/model/media/biblioteca.cpp \
		src/model/media/cd.cpp \
		src/model/media/fumetto.cpp \
		src/model/media/libro.cpp \
		src/model/media/media_audio.cpp \
		src/model/media/media_cartaceo.cpp \
		src/model/media/media_video.cpp \
		src/model/media/multimedia.cpp \
		src/model/media/periodico.cpp \
		src/model/media/serie_tv.cpp \
		src/model/persistence/JsonManager.cpp \
		src/model/visitors/VisitorWidget.cpp
QMAKE_TARGET  = Biblioteca
DESTDIR       = 
TARGET        = Biblioteca


first: all
####### Build rules

Biblioteca:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Biblioteca.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Biblioteca.pro
	$(QMAKE) -o Makefile Biblioteca.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Biblioteca.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Biblioteca.pro

qmake_all: FORCE


all: Makefile Biblioteca

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/gui/AdminPage.h src/gui/AdminDetailPage.h src/gui/BaseDetailPage.h src/gui/BasePage.h src/gui/EditMediaDialog.h src/gui/GalleryWidget.h src/gui/MediaBox.h src/gui/MediaDialog.h src/gui/SearchWidget.h src/gui/LoginPage.h src/gui/MainWindow.h src/gui/UserDetailPage.h src/gui/UserPage.h src/model/media/audiolibro.h src/model/media/biblioteca.h src/model/media/cd.h src/model/media/fumetto.h src/model/media/libro.h src/model/media/media_audio.h src/model/media/media_cartaceo.h src/model/media/media_video.h src/model/media/multimedia.h src/model/media/periodico.h src/model/media/serie_tv.h src/model/observers/JsonObserver.h src/model/persistence/JsonManager.h src/model/visitors/Visitor.h src/model/visitors/VisitorWidget.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/gui/AdminDetailPage.cpp src/gui/AdminPage.cpp src/gui/BaseDetailPage.cpp src/gui/BasePage.cpp src/gui/EditMediaDialog.cpp src/gui/GalleryWidget.cpp src/gui/MediaBox.cpp src/gui/MediaDialog.cpp src/gui/SearchWidget.cpp src/gui/LoginPage.cpp src/gui/MainWindow.cpp src/gui/UserDetailPage.cpp src/gui/UserPage.cpp src/model/media/audiolibro.cpp src/model/media/biblioteca.cpp src/model/media/cd.cpp src/model/media/fumetto.cpp src/model/media/libro.cpp src/model/media/media_audio.cpp src/model/media/media_cartaceo.cpp src/model/media/media_video.cpp src/model/media/multimedia.cpp src/model/media/periodico.cpp src/model/media/serie_tv.cpp src/model/persistence/JsonManager.cpp src/model/visitors/VisitorWidget.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_AdminPage.cpp build/moc/moc_AdminDetailPage.cpp build/moc/moc_BaseDetailPage.cpp build/moc/moc_BasePage.cpp build/moc/moc_EditMediaDialog.cpp build/moc/moc_GalleryWidget.cpp build/moc/moc_MediaBox.cpp build/moc/moc_MediaDialog.cpp build/moc/moc_SearchWidget.cpp build/moc/moc_LoginPage.cpp build/moc/moc_MainWindow.cpp build/moc/moc_UserDetailPage.cpp build/moc/moc_UserPage.cpp build/moc/moc_JsonManager.cpp build/moc/moc_VisitorWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_AdminPage.cpp build/moc/moc_AdminDetailPage.cpp build/moc/moc_BaseDetailPage.cpp build/moc/moc_BasePage.cpp build/moc/moc_EditMediaDialog.cpp build/moc/moc_GalleryWidget.cpp build/moc/moc_MediaBox.cpp build/moc/moc_MediaDialog.cpp build/moc/moc_SearchWidget.cpp build/moc/moc_LoginPage.cpp build/moc/moc_MainWindow.cpp build/moc/moc_UserDetailPage.cpp build/moc/moc_UserPage.cpp build/moc/moc_JsonManager.cpp build/moc/moc_VisitorWidget.cpp
build/moc/moc_AdminPage.cpp: src/gui/AdminPage.h \
		src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/AdminPage.h -o build/moc/moc_AdminPage.cpp

build/moc/moc_AdminDetailPage.cpp: src/gui/AdminDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/AdminDetailPage.h -o build/moc/moc_AdminDetailPage.cpp

build/moc/moc_BaseDetailPage.cpp: src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/BaseDetailPage.h -o build/moc/moc_BaseDetailPage.cpp

build/moc/moc_BasePage.cpp: src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/BasePage.h -o build/moc/moc_BasePage.cpp

build/moc/moc_EditMediaDialog.cpp: src/gui/EditMediaDialog.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/EditMediaDialog.h -o build/moc/moc_EditMediaDialog.cpp

build/moc/moc_GalleryWidget.cpp: src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/GalleryWidget.h -o build/moc/moc_GalleryWidget.cpp

build/moc/moc_MediaBox.cpp: src/gui/MediaBox.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/MediaBox.h -o build/moc/moc_MediaBox.cpp

build/moc/moc_MediaDialog.cpp: src/gui/MediaDialog.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/MediaDialog.h -o build/moc/moc_MediaDialog.cpp

build/moc/moc_SearchWidget.cpp: src/gui/SearchWidget.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/SearchWidget.h -o build/moc/moc_SearchWidget.cpp

build/moc/moc_LoginPage.cpp: src/gui/LoginPage.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/LoginPage.h -o build/moc/moc_LoginPage.cpp

build/moc/moc_MainWindow.cpp: src/gui/MainWindow.h \
		src/gui/LoginPage.h \
		src/gui/UserPage.h \
		src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		src/gui/AdminPage.h \
		src/gui/UserDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/gui/AdminDetailPage.h \
		src/model/persistence/JsonManager.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/MainWindow.h -o build/moc/moc_MainWindow.cpp

build/moc/moc_UserDetailPage.cpp: src/gui/UserDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/UserDetailPage.h -o build/moc/moc_UserDetailPage.cpp

build/moc/moc_UserPage.cpp: src/gui/UserPage.h \
		src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/UserPage.h -o build/moc/moc_UserPage.cpp

build/moc/moc_JsonManager.cpp: src/model/persistence/JsonManager.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/model/persistence/JsonManager.h -o build/moc/moc_JsonManager.cpp

build/moc/moc_VisitorWidget.cpp: src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/aldo/Scrivania/Biblioteca/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/aldo/Scrivania/Biblioteca -I/home/aldo/Scrivania/Biblioteca -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/model/visitors/VisitorWidget.h -o build/moc/moc_VisitorWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/main.o: src/main.cpp src/gui/MainWindow.h \
		src/gui/LoginPage.h \
		src/gui/UserPage.h \
		src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		src/gui/AdminPage.h \
		src/gui/UserDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/gui/AdminDetailPage.h \
		src/model/persistence/JsonManager.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/AdminDetailPage.o: src/gui/AdminDetailPage.cpp src/gui/AdminDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h \
		src/model/media/biblioteca.h \
		src/gui/EditMediaDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/AdminDetailPage.o src/gui/AdminDetailPage.cpp

build/obj/AdminPage.o: src/gui/AdminPage.cpp src/gui/AdminPage.h \
		src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		src/model/persistence/JsonManager.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h \
		src/gui/MediaDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/AdminPage.o src/gui/AdminPage.cpp

build/obj/BaseDetailPage.o: src/gui/BaseDetailPage.cpp src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h \
		src/model/media/biblioteca.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/BaseDetailPage.o src/gui/BaseDetailPage.cpp

build/obj/BasePage.o: src/gui/BasePage.cpp src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/BasePage.o src/gui/BasePage.cpp

build/obj/EditMediaDialog.o: src/gui/EditMediaDialog.cpp src/gui/EditMediaDialog.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/EditMediaDialog.o src/gui/EditMediaDialog.cpp

build/obj/GalleryWidget.o: src/gui/GalleryWidget.cpp src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		src/gui/MediaBox.h \
		src/model/media/media_cartaceo.h \
		src/model/media/media_fisico.h \
		src/model/media/libro.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/GalleryWidget.o src/gui/GalleryWidget.cpp

build/obj/MediaBox.o: src/gui/MediaBox.cpp src/gui/MediaBox.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/MediaBox.o src/gui/MediaBox.cpp

build/obj/MediaDialog.o: src/gui/MediaDialog.cpp src/gui/MediaDialog.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/MediaDialog.o src/gui/MediaDialog.cpp

build/obj/SearchWidget.o: src/gui/SearchWidget.cpp src/gui/SearchWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/SearchWidget.o src/gui/SearchWidget.cpp

build/obj/LoginPage.o: src/gui/LoginPage.cpp src/gui/LoginPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/LoginPage.o src/gui/LoginPage.cpp

build/obj/MainWindow.o: src/gui/MainWindow.cpp src/gui/MainWindow.h \
		src/gui/LoginPage.h \
		src/gui/UserPage.h \
		src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h \
		src/gui/AdminPage.h \
		src/gui/UserDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/gui/AdminDetailPage.h \
		src/model/persistence/JsonManager.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/MainWindow.o src/gui/MainWindow.cpp

build/obj/UserDetailPage.o: src/gui/UserDetailPage.cpp src/gui/UserDetailPage.h \
		src/gui/BaseDetailPage.h \
		src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/UserDetailPage.o src/gui/UserDetailPage.cpp

build/obj/UserPage.o: src/gui/UserPage.cpp src/gui/UserPage.h \
		src/gui/BasePage.h \
		src/gui/SearchWidget.h \
		src/gui/GalleryWidget.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/UserPage.o src/gui/UserPage.cpp

build/obj/audiolibro.o: src/model/media/audiolibro.cpp src/model/media/audiolibro.h \
		src/model/media/media_audio.h \
		src/model/media/multimedia.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/audiolibro.o src/model/media/audiolibro.cpp

build/obj/biblioteca.o: src/model/media/biblioteca.cpp src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/biblioteca.o src/model/media/biblioteca.cpp

build/obj/cd.o: src/model/media/cd.cpp src/model/media/cd.h \
		src/model/media/media_audio.h \
		src/model/media/multimedia.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/cd.o src/model/media/cd.cpp

build/obj/fumetto.o: src/model/media/fumetto.cpp src/model/media/fumetto.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/fumetto.o src/model/media/fumetto.cpp

build/obj/libro.o: src/model/media/libro.cpp src/model/media/libro.h \
		src/model/media/media_cartaceo.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/libro.o src/model/media/libro.cpp

build/obj/media_audio.o: src/model/media/media_audio.cpp src/model/media/media_audio.h \
		src/model/media/multimedia.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/media_audio.o src/model/media/media_audio.cpp

build/obj/media_cartaceo.o: src/model/media/media_cartaceo.cpp src/model/media/media_cartaceo.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/media_cartaceo.o src/model/media/media_cartaceo.cpp

build/obj/media_video.o: src/model/media/media_video.cpp src/model/media/media_video.h \
		src/model/media/multimedia.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/media_video.o src/model/media/media_video.cpp

build/obj/multimedia.o: src/model/media/multimedia.cpp src/model/media/multimedia.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/multimedia.o src/model/media/multimedia.cpp

build/obj/periodico.o: src/model/media/periodico.cpp src/model/media/periodico.h \
		src/model/media/media_cartaceo.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/periodico.o src/model/media/periodico.cpp

build/obj/serie_tv.o: src/model/media/serie_tv.cpp src/model/media/serie_tv.h \
		src/model/media/media_video.h \
		src/model/media/multimedia.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/serie_tv.o src/model/media/serie_tv.cpp

build/obj/JsonManager.o: src/model/persistence/JsonManager.cpp src/model/persistence/JsonManager.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h \
		src/model/media/biblioteca.h \
		src/model/visitors/Visitor.h \
		src/model/observers/JsonObserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/JsonManager.o src/model/persistence/JsonManager.cpp

build/obj/VisitorWidget.o: src/model/visitors/VisitorWidget.cpp src/model/visitors/VisitorWidget.h \
		src/model/visitors/Visitor.h \
		src/model/media/libro.h \
		src/model/media/media_cartaceo.h \
		src/model/media/biblioteca.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/VisitorWidget.o src/model/visitors/VisitorWidget.cpp

build/obj/moc_AdminPage.o: build/moc/moc_AdminPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_AdminPage.o build/moc/moc_AdminPage.cpp

build/obj/moc_AdminDetailPage.o: build/moc/moc_AdminDetailPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_AdminDetailPage.o build/moc/moc_AdminDetailPage.cpp

build/obj/moc_BaseDetailPage.o: build/moc/moc_BaseDetailPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_BaseDetailPage.o build/moc/moc_BaseDetailPage.cpp

build/obj/moc_BasePage.o: build/moc/moc_BasePage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_BasePage.o build/moc/moc_BasePage.cpp

build/obj/moc_EditMediaDialog.o: build/moc/moc_EditMediaDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_EditMediaDialog.o build/moc/moc_EditMediaDialog.cpp

build/obj/moc_GalleryWidget.o: build/moc/moc_GalleryWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_GalleryWidget.o build/moc/moc_GalleryWidget.cpp

build/obj/moc_MediaBox.o: build/moc/moc_MediaBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_MediaBox.o build/moc/moc_MediaBox.cpp

build/obj/moc_MediaDialog.o: build/moc/moc_MediaDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_MediaDialog.o build/moc/moc_MediaDialog.cpp

build/obj/moc_SearchWidget.o: build/moc/moc_SearchWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_SearchWidget.o build/moc/moc_SearchWidget.cpp

build/obj/moc_LoginPage.o: build/moc/moc_LoginPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_LoginPage.o build/moc/moc_LoginPage.cpp

build/obj/moc_MainWindow.o: build/moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_MainWindow.o build/moc/moc_MainWindow.cpp

build/obj/moc_UserDetailPage.o: build/moc/moc_UserDetailPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_UserDetailPage.o build/moc/moc_UserDetailPage.cpp

build/obj/moc_UserPage.o: build/moc/moc_UserPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_UserPage.o build/moc/moc_UserPage.cpp

build/obj/moc_JsonManager.o: build/moc/moc_JsonManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_JsonManager.o build/moc/moc_JsonManager.cpp

build/obj/moc_VisitorWidget.o: build/moc/moc_VisitorWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_VisitorWidget.o build/moc/moc_VisitorWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

